################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../NTLsrc/BerlekampTest.c \
../NTLsrc/BitMatTest.c \
../NTLsrc/CanZassTest.c \
../NTLsrc/CharPolyTest.c \
../NTLsrc/CheckCLZL.c \
../NTLsrc/CheckCLZLAux.c \
../NTLsrc/CheckLL.c \
../NTLsrc/CheckLLAux.c \
../NTLsrc/CheckPCLMUL.c \
../NTLsrc/DispSettings.c \
../NTLsrc/ExceptionTest.c \
../NTLsrc/FFT.c \
../NTLsrc/FacVec.c \
../NTLsrc/GF2.c \
../NTLsrc/GF2E.c \
../NTLsrc/GF2EX.c \
../NTLsrc/GF2EXFactoring.c \
../NTLsrc/GF2EXTest.c \
../NTLsrc/GF2X.c \
../NTLsrc/GF2X1.c \
../NTLsrc/GF2XFactoring.c \
../NTLsrc/GF2XTest.c \
../NTLsrc/GF2XTimeTest.c \
../NTLsrc/GF2XVec.c \
../NTLsrc/G_LLL_FP.c \
../NTLsrc/G_LLL_QP.c \
../NTLsrc/G_LLL_RR.c \
../NTLsrc/G_LLL_XD.c \
../NTLsrc/GetPID.c \
../NTLsrc/GetPID1.c \
../NTLsrc/GetPID2.c \
../NTLsrc/GetTime.c \
../NTLsrc/GetTime1.c \
../NTLsrc/GetTime2.c \
../NTLsrc/GetTime3.c \
../NTLsrc/GetTime4.c \
../NTLsrc/GetTime5.c \
../NTLsrc/HNF.c \
../NTLsrc/InitSettings.c \
../NTLsrc/LLL.c \
../NTLsrc/LLLTest.c \
../NTLsrc/LLL_FP.c \
../NTLsrc/LLL_QP.c \
../NTLsrc/LLL_RR.c \
../NTLsrc/LLL_XD.c \
../NTLsrc/MakeDesc.c \
../NTLsrc/MakeDescAux.c \
../NTLsrc/MatrixTest.c \
../NTLsrc/MoreFacTest.c \
../NTLsrc/MulTimeTest.c \
../NTLsrc/Poly1TimeTest.c \
../NTLsrc/PolyTimeTest.c \
../NTLsrc/QuadTest.c \
../NTLsrc/QuickTest.c \
../NTLsrc/RR.c \
../NTLsrc/RRTest.c \
../NTLsrc/TestGetPID.c \
../NTLsrc/TestGetTime.c \
../NTLsrc/ThreadTest.c \
../NTLsrc/Timing.c \
../NTLsrc/WordVector.c \
../NTLsrc/ZZ.c \
../NTLsrc/ZZVec.c \
../NTLsrc/ZZX.c \
../NTLsrc/ZZX1.c \
../NTLsrc/ZZXCharPoly.c \
../NTLsrc/ZZXFacTest.c \
../NTLsrc/ZZXFactoring.c \
../NTLsrc/ZZ_p.c \
../NTLsrc/ZZ_pE.c \
../NTLsrc/ZZ_pEX.c \
../NTLsrc/ZZ_pEXFactoring.c \
../NTLsrc/ZZ_pEXTest.c \
../NTLsrc/ZZ_pX.c \
../NTLsrc/ZZ_pX1.c \
../NTLsrc/ZZ_pXCharPoly.c \
../NTLsrc/ZZ_pXFactoring.c \
../NTLsrc/ctools.c \
../NTLsrc/fileio.c \
../NTLsrc/gen_gmp_aux.c \
../NTLsrc/lip.c \
../NTLsrc/lzz_p.c \
../NTLsrc/lzz_pE.c \
../NTLsrc/lzz_pEX.c \
../NTLsrc/lzz_pEXFactoring.c \
../NTLsrc/lzz_pEXTest.c \
../NTLsrc/lzz_pX.c \
../NTLsrc/lzz_pX1.c \
../NTLsrc/lzz_pXCharPoly.c \
../NTLsrc/lzz_pXFactoring.c \
../NTLsrc/mat_GF2.c \
../NTLsrc/mat_GF2E.c \
../NTLsrc/mat_RR.c \
../NTLsrc/mat_ZZ.c \
../NTLsrc/mat_ZZ_p.c \
../NTLsrc/mat_ZZ_pE.c \
../NTLsrc/mat_lzz_p.c \
../NTLsrc/mat_lzz_pE.c \
../NTLsrc/mat_poly_ZZ.c \
../NTLsrc/mat_poly_ZZ_p.c \
../NTLsrc/mat_poly_lzz_p.c \
../NTLsrc/newnames.c \
../NTLsrc/quad_float.c \
../NTLsrc/subset.c \
../NTLsrc/thread.c \
../NTLsrc/tools.c \
../NTLsrc/vec_GF2.c \
../NTLsrc/vec_GF2E.c \
../NTLsrc/vec_RR.c \
../NTLsrc/vec_ZZ.c \
../NTLsrc/vec_ZZ_p.c \
../NTLsrc/vec_ZZ_pE.c \
../NTLsrc/vec_lzz_p.c \
../NTLsrc/vec_lzz_pE.c \
../NTLsrc/xdouble.c 

OBJS += \
./NTLsrc/BerlekampTest.o \
./NTLsrc/BitMatTest.o \
./NTLsrc/CanZassTest.o \
./NTLsrc/CharPolyTest.o \
./NTLsrc/CheckCLZL.o \
./NTLsrc/CheckCLZLAux.o \
./NTLsrc/CheckLL.o \
./NTLsrc/CheckLLAux.o \
./NTLsrc/CheckPCLMUL.o \
./NTLsrc/DispSettings.o \
./NTLsrc/ExceptionTest.o \
./NTLsrc/FFT.o \
./NTLsrc/FacVec.o \
./NTLsrc/GF2.o \
./NTLsrc/GF2E.o \
./NTLsrc/GF2EX.o \
./NTLsrc/GF2EXFactoring.o \
./NTLsrc/GF2EXTest.o \
./NTLsrc/GF2X.o \
./NTLsrc/GF2X1.o \
./NTLsrc/GF2XFactoring.o \
./NTLsrc/GF2XTest.o \
./NTLsrc/GF2XTimeTest.o \
./NTLsrc/GF2XVec.o \
./NTLsrc/G_LLL_FP.o \
./NTLsrc/G_LLL_QP.o \
./NTLsrc/G_LLL_RR.o \
./NTLsrc/G_LLL_XD.o \
./NTLsrc/GetPID.o \
./NTLsrc/GetPID1.o \
./NTLsrc/GetPID2.o \
./NTLsrc/GetTime.o \
./NTLsrc/GetTime1.o \
./NTLsrc/GetTime2.o \
./NTLsrc/GetTime3.o \
./NTLsrc/GetTime4.o \
./NTLsrc/GetTime5.o \
./NTLsrc/HNF.o \
./NTLsrc/InitSettings.o \
./NTLsrc/LLL.o \
./NTLsrc/LLLTest.o \
./NTLsrc/LLL_FP.o \
./NTLsrc/LLL_QP.o \
./NTLsrc/LLL_RR.o \
./NTLsrc/LLL_XD.o \
./NTLsrc/MakeDesc.o \
./NTLsrc/MakeDescAux.o \
./NTLsrc/MatrixTest.o \
./NTLsrc/MoreFacTest.o \
./NTLsrc/MulTimeTest.o \
./NTLsrc/Poly1TimeTest.o \
./NTLsrc/PolyTimeTest.o \
./NTLsrc/QuadTest.o \
./NTLsrc/QuickTest.o \
./NTLsrc/RR.o \
./NTLsrc/RRTest.o \
./NTLsrc/TestGetPID.o \
./NTLsrc/TestGetTime.o \
./NTLsrc/ThreadTest.o \
./NTLsrc/Timing.o \
./NTLsrc/WordVector.o \
./NTLsrc/ZZ.o \
./NTLsrc/ZZVec.o \
./NTLsrc/ZZX.o \
./NTLsrc/ZZX1.o \
./NTLsrc/ZZXCharPoly.o \
./NTLsrc/ZZXFacTest.o \
./NTLsrc/ZZXFactoring.o \
./NTLsrc/ZZ_p.o \
./NTLsrc/ZZ_pE.o \
./NTLsrc/ZZ_pEX.o \
./NTLsrc/ZZ_pEXFactoring.o \
./NTLsrc/ZZ_pEXTest.o \
./NTLsrc/ZZ_pX.o \
./NTLsrc/ZZ_pX1.o \
./NTLsrc/ZZ_pXCharPoly.o \
./NTLsrc/ZZ_pXFactoring.o \
./NTLsrc/ctools.o \
./NTLsrc/fileio.o \
./NTLsrc/gen_gmp_aux.o \
./NTLsrc/lip.o \
./NTLsrc/lzz_p.o \
./NTLsrc/lzz_pE.o \
./NTLsrc/lzz_pEX.o \
./NTLsrc/lzz_pEXFactoring.o \
./NTLsrc/lzz_pEXTest.o \
./NTLsrc/lzz_pX.o \
./NTLsrc/lzz_pX1.o \
./NTLsrc/lzz_pXCharPoly.o \
./NTLsrc/lzz_pXFactoring.o \
./NTLsrc/mat_GF2.o \
./NTLsrc/mat_GF2E.o \
./NTLsrc/mat_RR.o \
./NTLsrc/mat_ZZ.o \
./NTLsrc/mat_ZZ_p.o \
./NTLsrc/mat_ZZ_pE.o \
./NTLsrc/mat_lzz_p.o \
./NTLsrc/mat_lzz_pE.o \
./NTLsrc/mat_poly_ZZ.o \
./NTLsrc/mat_poly_ZZ_p.o \
./NTLsrc/mat_poly_lzz_p.o \
./NTLsrc/newnames.o \
./NTLsrc/quad_float.o \
./NTLsrc/subset.o \
./NTLsrc/thread.o \
./NTLsrc/tools.o \
./NTLsrc/vec_GF2.o \
./NTLsrc/vec_GF2E.o \
./NTLsrc/vec_RR.o \
./NTLsrc/vec_ZZ.o \
./NTLsrc/vec_ZZ_p.o \
./NTLsrc/vec_ZZ_pE.o \
./NTLsrc/vec_lzz_p.o \
./NTLsrc/vec_lzz_pE.o \
./NTLsrc/xdouble.o 

C_DEPS += \
./NTLsrc/BerlekampTest.d \
./NTLsrc/BitMatTest.d \
./NTLsrc/CanZassTest.d \
./NTLsrc/CharPolyTest.d \
./NTLsrc/CheckCLZL.d \
./NTLsrc/CheckCLZLAux.d \
./NTLsrc/CheckLL.d \
./NTLsrc/CheckLLAux.d \
./NTLsrc/CheckPCLMUL.d \
./NTLsrc/DispSettings.d \
./NTLsrc/ExceptionTest.d \
./NTLsrc/FFT.d \
./NTLsrc/FacVec.d \
./NTLsrc/GF2.d \
./NTLsrc/GF2E.d \
./NTLsrc/GF2EX.d \
./NTLsrc/GF2EXFactoring.d \
./NTLsrc/GF2EXTest.d \
./NTLsrc/GF2X.d \
./NTLsrc/GF2X1.d \
./NTLsrc/GF2XFactoring.d \
./NTLsrc/GF2XTest.d \
./NTLsrc/GF2XTimeTest.d \
./NTLsrc/GF2XVec.d \
./NTLsrc/G_LLL_FP.d \
./NTLsrc/G_LLL_QP.d \
./NTLsrc/G_LLL_RR.d \
./NTLsrc/G_LLL_XD.d \
./NTLsrc/GetPID.d \
./NTLsrc/GetPID1.d \
./NTLsrc/GetPID2.d \
./NTLsrc/GetTime.d \
./NTLsrc/GetTime1.d \
./NTLsrc/GetTime2.d \
./NTLsrc/GetTime3.d \
./NTLsrc/GetTime4.d \
./NTLsrc/GetTime5.d \
./NTLsrc/HNF.d \
./NTLsrc/InitSettings.d \
./NTLsrc/LLL.d \
./NTLsrc/LLLTest.d \
./NTLsrc/LLL_FP.d \
./NTLsrc/LLL_QP.d \
./NTLsrc/LLL_RR.d \
./NTLsrc/LLL_XD.d \
./NTLsrc/MakeDesc.d \
./NTLsrc/MakeDescAux.d \
./NTLsrc/MatrixTest.d \
./NTLsrc/MoreFacTest.d \
./NTLsrc/MulTimeTest.d \
./NTLsrc/Poly1TimeTest.d \
./NTLsrc/PolyTimeTest.d \
./NTLsrc/QuadTest.d \
./NTLsrc/QuickTest.d \
./NTLsrc/RR.d \
./NTLsrc/RRTest.d \
./NTLsrc/TestGetPID.d \
./NTLsrc/TestGetTime.d \
./NTLsrc/ThreadTest.d \
./NTLsrc/Timing.d \
./NTLsrc/WordVector.d \
./NTLsrc/ZZ.d \
./NTLsrc/ZZVec.d \
./NTLsrc/ZZX.d \
./NTLsrc/ZZX1.d \
./NTLsrc/ZZXCharPoly.d \
./NTLsrc/ZZXFacTest.d \
./NTLsrc/ZZXFactoring.d \
./NTLsrc/ZZ_p.d \
./NTLsrc/ZZ_pE.d \
./NTLsrc/ZZ_pEX.d \
./NTLsrc/ZZ_pEXFactoring.d \
./NTLsrc/ZZ_pEXTest.d \
./NTLsrc/ZZ_pX.d \
./NTLsrc/ZZ_pX1.d \
./NTLsrc/ZZ_pXCharPoly.d \
./NTLsrc/ZZ_pXFactoring.d \
./NTLsrc/ctools.d \
./NTLsrc/fileio.d \
./NTLsrc/gen_gmp_aux.d \
./NTLsrc/lip.d \
./NTLsrc/lzz_p.d \
./NTLsrc/lzz_pE.d \
./NTLsrc/lzz_pEX.d \
./NTLsrc/lzz_pEXFactoring.d \
./NTLsrc/lzz_pEXTest.d \
./NTLsrc/lzz_pX.d \
./NTLsrc/lzz_pX1.d \
./NTLsrc/lzz_pXCharPoly.d \
./NTLsrc/lzz_pXFactoring.d \
./NTLsrc/mat_GF2.d \
./NTLsrc/mat_GF2E.d \
./NTLsrc/mat_RR.d \
./NTLsrc/mat_ZZ.d \
./NTLsrc/mat_ZZ_p.d \
./NTLsrc/mat_ZZ_pE.d \
./NTLsrc/mat_lzz_p.d \
./NTLsrc/mat_lzz_pE.d \
./NTLsrc/mat_poly_ZZ.d \
./NTLsrc/mat_poly_ZZ_p.d \
./NTLsrc/mat_poly_lzz_p.d \
./NTLsrc/newnames.d \
./NTLsrc/quad_float.d \
./NTLsrc/subset.d \
./NTLsrc/thread.d \
./NTLsrc/tools.d \
./NTLsrc/vec_GF2.d \
./NTLsrc/vec_GF2E.d \
./NTLsrc/vec_RR.d \
./NTLsrc/vec_ZZ.d \
./NTLsrc/vec_ZZ_p.d \
./NTLsrc/vec_ZZ_pE.d \
./NTLsrc/vec_lzz_p.d \
./NTLsrc/vec_lzz_pE.d \
./NTLsrc/xdouble.d 


# Each subdirectory must supply rules for building sources it contributes
NTLsrc/%.o: ../NTLsrc/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


